from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 200)
        font = QtGui.QFont()
        Dialog.setFont(font)
        Dialog.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.closeButton = QtWidgets.QDialogButtonBox(Dialog)
        self.closeButton.setGeometry(QtCore.QRect(308, 160, 71, 23))
        self.closeButton.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.closeButton.setObjectName("closeButton")
        self.labelVersion = QtWidgets.QLabel(Dialog)
        self.labelVersion.setGeometry(QtCore.QRect(10, 10, 381, 21))
        self.labelVersion.setText("")
        self.labelVersion.setObjectName("labelVersion")
        self.labelAbout1 = QtWidgets.QLabel(Dialog)
        self.labelAbout1.setGeometry(QtCore.QRect(10, 40, 381, 21))
        self.labelAbout1.setObjectName("labelAbout1")
        self.labelAbout2 = QtWidgets.QLabel(Dialog)
        self.labelAbout2.setGeometry(QtCore.QRect(10, 60, 381, 20))
        self.labelAbout2.setObjectName("labelAbout2")
        self.labelSourceCodeLink = QtWidgets.QLabel(Dialog)
        self.labelSourceCodeLink.setGeometry(QtCore.QRect(10, 110, 381, 20))
        self.labelSourceCodeLink.setText("")
        self.labelSourceCodeLink.setOpenExternalLinks(True)
        self.labelSourceCodeLink.setObjectName("labelSourceCodeLink")
        self.labelLicenseLink = QtWidgets.QLabel(Dialog)
        self.labelLicenseLink.setGeometry(QtCore.QRect(10, 130, 381, 20))
        self.labelLicenseLink.setText("")
        self.labelLicenseLink.setOpenExternalLinks(True)
        self.labelLicenseLink.setObjectName("labelLicenseLink")
        self.labelWebsiteLink = QtWidgets.QLabel(Dialog)
        self.labelWebsiteLink.setGeometry(QtCore.QRect(10, 90, 381, 20))
        self.labelWebsiteLink.setText("")
        self.labelWebsiteLink.setOpenExternalLinks(True)
        self.labelWebsiteLink.setObjectName("labelWebsiteLink")

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.closeButton, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "About", None, -1))
        self.labelAbout1.setText(QtWidgets.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" font-size:8.25pt;\">This program was written with Python and uses PySide2 for the front-end.</span></p></body></html>", None, -1))
        self.labelAbout2.setText(QtWidgets.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" font-size:8.25pt;\">This program is completely free, open source, and comes with no warranty.</span></p></body></html>", None, -1))

