from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 375)
        MainWindow.setMinimumSize(QtCore.QSize(600, 375))
        MainWindow.setWindowTitle("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelAddress = QtWidgets.QLabel(self.tab)
        self.labelAddress.setObjectName("labelAddress")
        self.verticalLayout_2.addWidget(self.labelAddress)
        self.Address = QtWidgets.QLineEdit(self.tab)
        self.Address.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Address.setStatusTip("")
        self.Address.setStyleSheet("")
        self.Address.setClearButtonEnabled(True)
        self.Address.setObjectName("Address")
        self.verticalLayout_2.addWidget(self.Address)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.labelStartDate = QtWidgets.QLabel(self.tab)
        self.labelStartDate.setObjectName("labelStartDate")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelStartDate)
        self.StartDate = QtWidgets.QLineEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StartDate.sizePolicy().hasHeightForWidth())
        self.StartDate.setSizePolicy(sizePolicy)
        self.StartDate.setText("")
        self.StartDate.setObjectName("StartDate")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.StartDate)
        self.horizontalLayout_6.addLayout(self.formLayout)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.labelEndDate = QtWidgets.QLabel(self.tab)
        self.labelEndDate.setObjectName("labelEndDate")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelEndDate)
        self.EndDate = QtWidgets.QLineEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EndDate.sizePolicy().hasHeightForWidth())
        self.EndDate.setSizePolicy(sizePolicy)
        self.EndDate.setObjectName("EndDate")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.EndDate)
        self.horizontalLayout_6.addLayout(self.formLayout_4)
        self.horizontalLayout.addLayout(self.horizontalLayout_6)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.CreateCSV = QtWidgets.QPushButton(self.tab)
        self.CreateCSV.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CreateCSV.sizePolicy().hasHeightForWidth())
        self.CreateCSV.setSizePolicy(sizePolicy)
        self.CreateCSV.setObjectName("CreateCSV")
        self.verticalLayout_4.addWidget(self.CreateCSV)
        self.GetBalance = QtWidgets.QPushButton(self.tab)
        self.GetBalance.setEnabled(False)
        self.GetBalance.setObjectName("GetBalance")
        self.verticalLayout_4.addWidget(self.GetBalance)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.output = QtWidgets.QTextBrowser(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output.sizePolicy().hasHeightForWidth())
        self.output.setSizePolicy(sizePolicy)
        self.output.setMinimumSize(QtCore.QSize(500, 150))
        self.output.setObjectName("output")
        self.verticalLayout.addWidget(self.output)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.labelABNickname = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelABNickname.sizePolicy().hasHeightForWidth())
        self.labelABNickname.setSizePolicy(sizePolicy)
        self.labelABNickname.setMaximumSize(QtCore.QSize(75, 16777215))
        self.labelABNickname.setObjectName("labelABNickname")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelABNickname)
        self.labelABAddress = QtWidgets.QLabel(self.tab_2)
        self.labelABAddress.setObjectName("labelABAddress")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.labelABAddress)
        self.ABNickname = QtWidgets.QLineEdit(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ABNickname.sizePolicy().hasHeightForWidth())
        self.ABNickname.setSizePolicy(sizePolicy)
        self.ABNickname.setMinimumSize(QtCore.QSize(50, 0))
        self.ABNickname.setMaximumSize(QtCore.QSize(75, 16777215))
        self.ABNickname.setObjectName("ABNickname")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.ABNickname)
        self.ABAddress = QtWidgets.QLineEdit(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ABAddress.sizePolicy().hasHeightForWidth())
        self.ABAddress.setSizePolicy(sizePolicy)
        self.ABAddress.setMinimumSize(QtCore.QSize(450, 0))
        self.ABAddress.setStyleSheet("")
        self.ABAddress.setClearButtonEnabled(True)
        self.ABAddress.setObjectName("ABAddress")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ABAddress)
        self.verticalLayout_5.addLayout(self.formLayout_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.addAddress = QtWidgets.QPushButton(self.tab_2)
        self.addAddress.setEnabled(False)
        self.addAddress.setObjectName("addAddress")
        self.horizontalLayout_2.addWidget(self.addAddress)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.tableAddresses = QtWidgets.QTableView(self.tab_2)
        self.tableAddresses.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.tableAddresses.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableAddresses.setObjectName("tableAddresses")
        self.verticalLayout_5.addWidget(self.tableAddresses)
        self.verticalLayout_9.addLayout(self.verticalLayout_5)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.layoutWidget = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 291, 211))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.labelSource = QtWidgets.QLabel(self.layoutWidget)
        self.labelSource.setObjectName("labelSource")
        self.verticalLayout_8.addWidget(self.labelSource)
        self.Source = QtWidgets.QLineEdit(self.layoutWidget)
        self.Source.setObjectName("Source")
        self.verticalLayout_8.addWidget(self.Source)
        self.labelMemo = QtWidgets.QLabel(self.layoutWidget)
        self.labelMemo.setObjectName("labelMemo")
        self.verticalLayout_8.addWidget(self.labelMemo)
        self.Memo = QtWidgets.QLineEdit(self.layoutWidget)
        self.Memo.setObjectName("Memo")
        self.verticalLayout_8.addWidget(self.Memo)
        self.labelMinThresh = QtWidgets.QLabel(self.layoutWidget)
        self.labelMinThresh.setObjectName("labelMinThresh")
        self.verticalLayout_8.addWidget(self.labelMinThresh)
        self.MinThresh = QtWidgets.QLineEdit(self.layoutWidget)
        self.MinThresh.setMaximumSize(QtCore.QSize(100, 16777215))
        self.MinThresh.setObjectName("MinThresh")
        self.verticalLayout_8.addWidget(self.MinThresh)
        self.labelMaxThresh = QtWidgets.QLabel(self.layoutWidget)
        self.labelMaxThresh.setObjectName("labelMaxThresh")
        self.verticalLayout_8.addWidget(self.labelMaxThresh)
        self.MaxThresh = QtWidgets.QLineEdit(self.layoutWidget)
        self.MaxThresh.setMaximumSize(QtCore.QSize(100, 16777215))
        self.MaxThresh.setObjectName("MaxThresh")
        self.verticalLayout_8.addWidget(self.MaxThresh)
        self.horizontalLayout_4.addLayout(self.verticalLayout_8)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.labelTheme = QtWidgets.QLabel(self.layoutWidget)
        self.labelTheme.setObjectName("labelTheme")
        self.verticalLayout_7.addWidget(self.labelTheme)
        self.radioButtonLightMode = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButtonLightMode.setObjectName("radioButtonLightMode")
        self.verticalLayout_7.addWidget(self.radioButtonLightMode)
        self.radioButtonDarkMode = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButtonDarkMode.setObjectName("radioButtonDarkMode")
        self.verticalLayout_7.addWidget(self.radioButtonDarkMode)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.SaveSettings = QtWidgets.QPushButton(self.layoutWidget)
        self.SaveSettings.setObjectName("SaveSettings")
        self.horizontalLayout_3.addWidget(self.SaveSettings)
        self.resetButton = QtWidgets.QPushButton(self.layoutWidget)
        self.resetButton.setToolTip("")
        self.resetButton.setObjectName("resetButton")
        self.horizontalLayout_3.addWidget(self.resetButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.tab_3, "")
        self.horizontalLayout_5.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionCheck_for_updates = QtWidgets.QAction(MainWindow)
        self.actionCheck_for_updates.setObjectName("actionCheck_for_updates")
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionCheck_for_updates)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.Address)
        MainWindow.setTabOrder(self.Address, self.StartDate)
        MainWindow.setTabOrder(self.StartDate, self.EndDate)
        MainWindow.setTabOrder(self.EndDate, self.CreateCSV)
        MainWindow.setTabOrder(self.CreateCSV, self.GetBalance)
        MainWindow.setTabOrder(self.GetBalance, self.output)
        MainWindow.setTabOrder(self.output, self.ABNickname)
        MainWindow.setTabOrder(self.ABNickname, self.ABAddress)
        MainWindow.setTabOrder(self.ABAddress, self.addAddress)
        MainWindow.setTabOrder(self.addAddress, self.tableAddresses)
        MainWindow.setTabOrder(self.tableAddresses, self.Source)
        MainWindow.setTabOrder(self.Source, self.Memo)
        MainWindow.setTabOrder(self.Memo, self.MinThresh)
        MainWindow.setTabOrder(self.MinThresh, self.MaxThresh)
        MainWindow.setTabOrder(self.MaxThresh, self.radioButtonLightMode)
        MainWindow.setTabOrder(self.radioButtonLightMode, self.radioButtonDarkMode)
        MainWindow.setTabOrder(self.radioButtonDarkMode, self.SaveSettings)
        MainWindow.setTabOrder(self.SaveSettings, self.resetButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.labelAddress.setText(_translate("MainWindow", "Stellar Address"))
        self.Address.setToolTip(_translate("MainWindow", "Stellar Address (required): A Stellar address to receive transactions from"))
        self.labelStartDate.setText(_translate("MainWindow", "Start Date"))
        self.StartDate.setToolTip(_translate("MainWindow", "Start Date (required): The date of the oldest transaction received"))
        self.StartDate.setPlaceholderText(_translate("MainWindow", "YYYY-MM-DD"))
        self.labelEndDate.setText(_translate("MainWindow", "End Date"))
        self.EndDate.setToolTip(_translate("MainWindow", "End Date (optional): Create a range of transactions received with a specific end date"))
        self.EndDate.setPlaceholderText(_translate("MainWindow", "YYYY-MM-DD"))
        self.CreateCSV.setToolTip(_translate("MainWindow", "Create CSV file with chosen parameters"))
        self.CreateCSV.setText(_translate("MainWindow", "Create CSV"))
        self.GetBalance.setToolTip(_translate("MainWindow", "Print the balance"))
        self.GetBalance.setText(_translate("MainWindow", "Get Balance"))
        self.output.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600; text-decoration: underline;\">Information</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Stellar Address</span> (required): A Stellar address to receive transactions from</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Start Date</span> (required): The date of the oldest transaction received</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">End Date</span> (optional): Create a range of transactions received with a specific end date</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">______________________________________________________________________</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Main"))
        self.labelABNickname.setText(_translate("MainWindow", "Nickname"))
        self.labelABAddress.setText(_translate("MainWindow", "Stellar Address"))
        self.ABNickname.setToolTip(_translate("MainWindow", "Nickname (optional)"))
        self.ABAddress.setToolTip(_translate("MainWindow", "Stellar address (required)"))
        self.addAddress.setToolTip(_translate("MainWindow", "Add to address book"))
        self.addAddress.setText(_translate("MainWindow", "Add"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Address Book"))
        self.labelSource.setText(_translate("MainWindow", "Source"))
        self.labelMemo.setText(_translate("MainWindow", "Memo"))
        self.labelMinThresh.setText(_translate("MainWindow", "Minimum Threshold"))
        self.labelMaxThresh.setText(_translate("MainWindow", "Maximum Threshold"))
        self.labelTheme.setText(_translate("MainWindow", "Theme"))
        self.radioButtonLightMode.setText(_translate("MainWindow", "Light"))
        self.radioButtonDarkMode.setText(_translate("MainWindow", "Dark"))
        self.SaveSettings.setToolTip(_translate("MainWindow", "Save chosen settings"))
        self.SaveSettings.setText(_translate("MainWindow", "Save Settings"))
        self.resetButton.setText(_translate("MainWindow", "Reset"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Settings"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionCheck_for_updates.setText(_translate("MainWindow", "Check for updates"))
